//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfThrones.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GameOfThrones.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BooksTitle {
            get {
                return ResourceManager.GetString("BooksTitle", resourceCulture);
            }
        }
        
        internal static string CharactersTitle {
            get {
                return ResourceManager.GetString("CharactersTitle", resourceCulture);
            }
        }
        
        internal static string HousesTitle {
            get {
                return ResourceManager.GetString("HousesTitle", resourceCulture);
            }
        }
        
        internal static string BookPagesFormat {
            get {
                return ResourceManager.GetString("BookPagesFormat", resourceCulture);
            }
        }
        
        internal static string CharacterBornFormat {
            get {
                return ResourceManager.GetString("CharacterBornFormat", resourceCulture);
            }
        }
        
        internal static string CharacterNoBirthInformation {
            get {
                return ResourceManager.GetString("CharacterNoBirthInformation", resourceCulture);
            }
        }
        
        internal static string CharacterPlayedByFormat {
            get {
                return ResourceManager.GetString("CharacterPlayedByFormat", resourceCulture);
            }
        }
        
        internal static string CharacterNoPlayedByInformation {
            get {
                return ResourceManager.GetString("CharacterNoPlayedByInformation", resourceCulture);
            }
        }
        
        internal static string HouseWordsFormat {
            get {
                return ResourceManager.GetString("HouseWordsFormat", resourceCulture);
            }
        }
        
        internal static string HouseNoWordsInformation {
            get {
                return ResourceManager.GetString("HouseNoWordsInformation", resourceCulture);
            }
        }
        
        internal static string HouseCoatOfArmsFormat {
            get {
                return ResourceManager.GetString("HouseCoatOfArmsFormat", resourceCulture);
            }
        }
        
        internal static string HouseNoCoatOfArmsInformation {
            get {
                return ResourceManager.GetString("HouseNoCoatOfArmsInformation", resourceCulture);
            }
        }
    }
}
